#pragma once
#include <stdio.h>
#include <windows.h>
#include <Wincrypt.h>
#include <vector>
#include <stdexcept>
#include <algorithm>
#include <tchar.h>
#include <string>
#include <fstream>

#include <iostream>
#include <fstream>
#include <vector>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/pkcs7.h>
#include <openssl/pem.h>
#include "atlbase.h"
#include "CertificateStoreOperation.h"